version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: ./Dockerfiles/DB.Dockerfile
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  node-app:
    build:
      context: .
      dockerfile: ./Dockerfiles/App.Dockerfile
    container_name: node_app
    image: nodeapp
    ports:
      - 3001:3001
      - 3002:3002
    volumes:
      - ./:/node/hello-node
    links:
      - mongodb:db
    environment:
      - DB_DRIVER=mongodb
      - DB_HOST=db
      - DB_NAME=team4
      - DB_PORT=27017
# run by "docker-compose up --build -d"
