version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: DB.Dockerfile
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  node-app:
    build:
      context: .
      dockerfile: App.Dockerfile
    container_name: node_app
    image: nodeapp
    ports:
      - 3000:3000
    volumes:
      - ./:/node/hello-node
    links:
      - mongodb:db
    env_file: ./config/.env
# run by "docker-compose up --build -d"